scheme: Gemini
math:
    katex:
      enable: true
custom_file_path:
  style: source/_data/custom.styl
# Disqus
disqus:
  enable: true
  shortname: nishuzumi
  count: true
  lazyload: false
  #post_meta_order: 0
codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  # See: https://github.com/chriskempson/tomorrow-theme
  # Add copy button on codeblock
  theme:
    light: monokai-sublime
    dark: monokai-sublime
  copy_button:
    enable: true  # *changed* 打开代码复制功能
    # Show text copy result.
    show_result: true
    # Available values: default | flat | mac
    style: mac  # *changed* 设为mac风格
fancybox: true
avatar:
  url: /images/avatar.jpg
  rounded: true
back2top:
  enable: true
  # Back to top in sidebar.
  sidebar: true
  # Scroll percent label in b2t button.
  scrollpercent: true